### PR TITLE
Ultra-light-threads using Argobots 

### PR DESCRIPTION
**Pull request by melsman**
This PR aims at using [Argobots](https://www.argobots.org/) for thread support in MLKit. Argobots can be configured with an execution stream per processor and a local pool (with work stealing) for each execution stream.  With this PR, MLKit can run with the following thread configurations:

1. Each MLKit thread corresponds to a posix thread (Pthread).
2. Each MLKit thread corresponds to an Argobot ultra-light thread (ULT). An ULT runs with its own stack.

### Compilation
To compile the MLKit with Argobots support, first copy the Argobots sources into a directory next to your MLKit sources:
```
$ cd ~/gits
$ git clone https://github.com/pmodels/argobots.git
```
Now, configure and build Argobots, as follows:
```
$ cd argobots
$ ./autogen.sh
$ ./configure
...
$ make
...
$ make install      // WARNING: You may not want to do this, in which case you need to 
                    // adjust the LD_LIBRARY_PATH for running the benchmarks later. Instead, maybe
                    // give a -prefix option to ./configure; see https://github.com/pmodels/argobots
```

You now need to configure and build the MLKit to use Argobots:
```
$ cd ~/gits/mlkit
$ git checkout argobots-integration
$ ./autobuild
$ ./configure --with-compiler=mlkit --with-argobots=~/gits/argobots
...
$ make mlkit && (cd src/Runtime; make runtimeSystemArPar.a) && make mlkit_basislibs
```

### Initial tests
Initial tests can be run as follows:
```
$ cd ~/gits/mlkit/test/parallelism
$ make clean && make all argo
```

### Benchmarks

To run benchmarks, first checkout the `mlkit-bench` repository into a directory next to your MLKit sources:

```
$ cd ~/gits
$ git clone https://github.com/melsman/mlkit-bench.git
```

Compile as follows:
```
$ cd mlkit-bench
$ make && (cd src/press; make)
```

To run the benchmarks, proceed as follows:
```
$ cd ~/gits/mlkit-bench/par-benchmarks
$ make clean report-arpar.json
```

To report the results, use the `mlkit-bench-press` tool:
```
$ make arpress
```

Here are the results on my Macbook pro 2016 (4(8) cores):
```
 | pname       | plen | real # argo | rss # argo | real # par | rss # par | real # seq | rss # seq |
 | fib         | 161  | 0.11 ±1%    | 26.8M ±0%  | 0.11 ±3%   | 2.7M ±0%  | 0.53 ±1%   | 2.1M ±0%  |
 | mandelbrot  | 355  | 0.25 ±4%    | 40.0M ±0%  | 0.20 ±1%   | 19.2M ±0% | 1.28 ±3%   | 8.4M ±0%  |
 | nqueens     | 243  | 0.79 ±3%    | 839M ±0%   | 0.77 ±2%   | 729M ±0%  | 1.84 ±4%   | 152M ±0%  |
 | pmsort      | 207  | 0.31 ±2%    | 245M ±0%   | 0.22 ±4%   | 226M ±0%  | 0.35 ±2%   | 81.9M ±0% |
 | primes      | 618  | 0.40 ±1%    | 85.9M ±0%  | 0.34 ±1%   | 53.7M ±0% | 1.23 ±1%   | 43.4M ±0% |
 | ray-orig    | 579  | 10.66 ±7%   | 1130M ±0%  | 5.14 ±0%   | 1208M ±0% | 11.33 ±2%  | 626M ±0%  |
 | ray         | 646  | 0.69 ±6%    | 218M ±0%   | 0.56 ±1%   | 183M ±0%  | 2.55 ±3%   | 28.3M ±0% |
 | seam-carve  | 1448 | 30.94 ±1%   | 5867M ±0%  | 26.64 ±1%  | 7781M ±0% | 11.97 ±6%  | 7367M ±0% |
 | filter      | 594  | 0.08 ±1%    | 356M ±0%   | 0.08 ±3%   | 326M ±0%  | 0.29 ±1%   | 325M ±0%  |
 | scan        | 595  | 0.14 ±0%    | 429M ±0%   | 0.14 ±1%   | 402M ±0%  | 0.54 ±2%   | 402M ±0%  |
 | sgm_scan    | 593  | 1.25 ±6%    | 822M ±0%   | 0.99 ±4%   | 799M ±0%  | 0.20 ±6%   | 322M ±0%  |
 | soboloption | 921  | 0.23 ±3%    | 34.7M ±0%  | 0.13 ±4%   | 13.0M ±0% | 0.45 ±2%   | 2.2M ±0%  |
 | sobolpi     | 893  | 0.21 ±2%    | 92.0M ±0%  | 0.18 ±1%   | 68.1M ±0% | 0.58 ±1%   | 18.1M ±0% |
 | vpmsort     | 226  | 0.14 ±2%    | 150M ±0%   | 0.10 ±2%   | 115M ±0%  | 0.30 ±2%   | 75.2M ±0% |
```

### CODE REVIEW

**Comment by athas** [comment]
The `make all argo` step fails for me.  I get this error repeated a bunch of times:

```
ld: ../../lib/runtimeSystemPar.a(Region-par.o):/home/athas/repos/mlkit/src/Runtime/Spawn.h:67: multiple definition of `threadinfo_key'; ../../lib/runtimeSystemPar.a(Runtime-par.o):/home/athas/repos/mlkit/src/Runtime/Spawn.h:67: first defined here
```

It appears Spawn.h:67 defines a global variable, meaning you cannot link two compilation units that both include this header file.

**Comment by athas** [comment]
I can fix it by changing the definition in Spawn.h to be `extern thread_key_t threadinfo_key` and then declaring `thread_key_t threadinfo_key` in Spawn.c.

**Comment by melsman** [comment]
Here are some final numbers demonstrating the differences between the sequential-based, Pthreads-based, and the Argobots-based runtimes.

```
 | pname       | real # mlton | real # seq | real # par1 | real # abt1 | real # par | real # abt | plen | 
 | fib         | 0.54 ±0%     | 0.44 ±3%   | 0.42 ±5%    | 0.74 ±4%    | 0.09 ±1%   | 0.09 ±6%   | 161  | 
 | mandelbrot  | 1.32 ±2%     | 1.35 ±3%   | 1.28 ±0%    | 1.84 ±4%    | 0.19 ±1%   | 0.28 ±2%   | 355  | 
 | nqueens     | 1.38 ±1%     | 1.58 ±3%   | 1.58 ±4%    | 2.74 ±3%    | 0.72 ±2%   | 0.69 ±2%   | 243  | 
 | pmsort      | 0.44 ±8%     | 0.34 ±10%  | 0.41 ±1%    | 1.52 ±2%    | 0.12 ±0%   | 0.42 ±0%   | 207  | 
 | primes      | 0.96 ±2%     | 1.16 ±2%   | 1.23 ±1%    | 3.12 ±2%    | 0.31 ±1%   | 0.37 ±1%   | 618  | 
 | ray-orig    | 4.05 ±3%     | 11.46 ±2%  | 13.50 ±1%   | 52.12 ±0%   | 3.32 ±1%   | 17.49 ±7%  | 579  | 
 | ray         | 3.94 ±2%     | 2.58 ±1%   | 2.59 ±7%    | 4.62 ±2%    | 0.54 ±1%   | 0.66 ±3%   | 646  | 
 | seam-carve  | 4.78 ±2%     | 14.29 ±5%  | 15.57 ±3%   | 27.18 ±2%   | 27.64 ±1%  | 32.41 ±7%  | 1448 | 
 | filter      | 0.25 ±5%     | 0.31 ±3%   | 0.31 ±4%    | 0.60 ±0%    | 0.09 ±4%   | 0.09 ±0%   | 594  | 
 | scan        | 0.37 ±2%     | 0.54 ±9%   | 0.55 ±5%    | 1.03 ±1%    | 0.15 ±8%   | 0.14 ±1%   | 595  | 
 | sgm_scan    | 0.23 ±14%    | 0.20 ±4%   | 0.22 ±6%    | 0.47 ±2%    | 1.13 ±1%   | 0.90 ±2%   | 593  | 
 | soboloption | 0.25 ±5%     | 0.44 ±1%   | 0.49 ±4%    | 1.33 ±1%    | 0.11 ±1%   | 0.34 ±2%   | 921  | 
 | sobolpi     | 0.38 ±4%     | 0.68 ±5%   | 0.59 ±2%    | 1.35 ±1%    | 0.14 ±2%   | 0.24 ±2%   | 893  | 
 | vpmsort     | 0.23 ±18%    | 0.28 ±7%   | 0.31 ±4%    | 0.74 ±1%    | 0.09 ±2%   | 0.18 ±2%   | 226  | 
```

Much to be said. First, let's compare the sequential runtimes from earlier (see above) and until recently:

```
 | pname        | real # seq | real # seq | real # mlton | 
 |              | old        | new        |              |  
 | fib          | 0.53 ±1%   | 0.44 ±3%   | 0.54 ±0%     | 
 | mandelbrot   | 1.28 ±3%   | 1.35 ±3%   | 1.32 ±2%     | 
 | nqueens      | 1.84 ±4%   | 1.58 ±3%   | 1.38 ±1%     | 
 | pmsort       | 0.35 ±2%   | 0.34 ±10%  | 0.44 ±8%     | 
 | primes       | 1.23 ±1%   | 1.16 ±2%   | 0.96 ±2%     | 
 | ray-orig     | 11.33 ±2%  | 11.46 ±2%  | 4.05 ±3%     | 
 | ray          | 2.55 ±3%   | 2.58 ±1%   | 3.94 ±2%     | 
 | seam-carve   | 11.97 ±6%  | 14.29 ±5%  | 4.78 ±2%     | 
 | filter       | 0.29 ±1%   | 0.31 ±3%   | 0.25 ±5%     | 
 | scan         | 0.54 ±2%   | 0.54 ±9%   | 0.37 ±2%     | 
 | sgm_scan     | 0.20 ±6%   | 0.20 ±4%   | 0.23 ±14%    | 
 | soboloption  | 0.45 ±2%   | 0.44 ±1%   | 0.25 ±5%     | 
 | sobolpi      | 0.58 ±1%   | 0.68 ±5%   | 0.38 ±4%     | 
 | vpmsort      | 0.30 ±2%   | 0.28 ±7%   | 0.23 ±18%    | 
```

Although the generated code is much cleaner now, the generated code is in some cases slower. We will later look into possibilities for improving runtimes further.

We now compare the Argobots-based and the Pthreads-based runtime. Except from one case (`sgm_scan`), the Pthreads-based runtime is better than the Argobots-based runtime. We need to investigate the difference when not controlling the generation of threads, as we do for most of the benchmarks here.

**Comment by melsman** [comment]
We will merge this PR into master now and create issues for further developments.

**Pull request merged**
